/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_.c
 * Generated on: Tue Feb 22 23:42:11 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstractionSWC.h"


extern uint8 ReadDoorSensor_PP_SR_DoorState;


const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC = &Rte_Instance_DoorSensorAbstractionSWC;




void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState (uint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
uint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
