/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_Type.h
 * Generated on: Tue Feb 22 23:42:11 EET
 ********************************************************************/

#ifndef RTE_DOORSENSORABSTRACTIONSWC_TYPE_H
#define RTE_DOORSENSORABSTRACTIONSWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define uint8_LowerLimit  (0U)
#define uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORSENSORABSTRACTIONSWC_TYPE_H */
