/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indication_SWC_.c
 * Generated on: Tue Feb 22 23:42:11 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_indication_SWC.h"



uint8 ReadDoorSensor_PP_SR_DoorState;

const Rte_CDS_DoorLock_indication_SWC Rte_Instance_DoorLock_indication_SWC = {
0
};

const Rte_CDS_DoorLock_indication_SWC * const Rte_Inst_DoorLock_indication_SWC = &Rte_Instance_DoorLock_indication_SWC;


uint8 DoorLock_indication_SWC_RP_SR_DoorState_DoorState_Buffer;
Std_ReturnType DoorLock_indication_SWC_RP_SR_DoorState_DoorState_Buffer_retcode = RTE_E_OK;
Std_ReturnType DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = 0;

Std_ReturnType Rte_Read_DoorLock_indication_SWC_RP_SR_DoorState_DoorState (uint8* DoorState)
{
	*DoorState =  ReadDoorSensor_PP_SR_DoorState;
	return DoorLock_indication_SWC_RP_SR_DoorState_DoorState_Buffer_retcode;
}
Std_ReturnType Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch (uint8 LedState)
{
	Std_ReturnType __result = DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(LedState);
	}
	__result = Led_Switch_runnable(LedState);
	return __result;
}
